spring.application.name=baised
spring.data.mongodb.uri=mongodb://localhost:27017/baised
server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
clerk.issuer=https://concise-cobra-88.clerk.accounts.dev
clerk.jwks.url=https://concise-cobra-88.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=i+lMYJGEjjG7ButWwS9iTgj/nxIpvy79


#file upload configs
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB


# Razorpay Configuration

razorpay.key.id=rzp_test_SPwlVMfNYHY6Zk
razorpay.key.secret=hWeQbNpZcwnonNy00H9F8Fyp